import React from "react";
import PropTypes from "prop-types";

import Header from "../../../components/Header";
import CookieConsent from "../../../components/CookieConsent";

import "./global.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Header />
        {children}
        <CookieConsent />
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};
