name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      # Remove other domain packages to prevent their build
      - name: Prepare Workspace
        run: |
          echo "Current directory contents:"
          ls -la domains/

          cp -r domains/access domains/access_backup
          rm -rf domains/excel domains/office domains/powerPlatform domains/word
          rm -rf domains/access
          mv domains/access_backup domains/access

          echo "Final directory contents:"
          ls -la domains/

      # Install dependencies at root and access domain
      - name: Install Dependencies
        run: |
          npm install
          cd domains/access
          npm install next-sitemap --save-dev

      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client

      # Create next-sitemap config if it doesn't exist
      - name: Create Sitemap Config
        run: |
          echo "/** @type {import('next-sitemap').IConfig} */
          module.exports = {
            siteUrl: 'https://gentle-hill-0be2d5700.azurestaticapps.net',
            generateRobotsTxt: true,
            changefreq: 'weekly',
            priority: 0.7,
            exclude: ['/api/*'],
            generateIndexSitemap: false,
          }" > domains/access/next-sitemap.config.js

      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            return await coredemo.getIDToken()
          result-encoding: string

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_HILL_0BE2D5700 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "."
          api_location: ""
          output_location: "domains/access/.next"
          app_build_command: |
            cd domains/access && 
            npm run build && 
            npx next-sitemap
          github_id_token: ${{ steps.idtoken.outputs.result }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_HILL_0BE2D5700 }}
          action: "close"
