name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "domains/access/**" # Only trigger on changes to access domain
      - "package.json"
      - "turbo.json"
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - "domains/access/**"
      - "package.json"
      - "turbo.json"

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      # Remove other domain packages to prevent their build
      - name: Prepare Workspace
        run: |
          # Keep only access domain and remove others
          cd domains
          mv access temp_access
          rm -rf *
          mv temp_access access

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client

      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            return await coredemo.getIDToken()
          result-encoding: string

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_HILL_0BE2D5700 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "." # Keep as root as per Azure setup
          api_location: "" # Empty for Next.js apps
          output_location: "domains/access/.next" # Specific to access domain
          app_build_command: "npm run build --filter=@experts/access" # Use turbo filter
          github_id_token: ${{ steps.idtoken.outputs.result }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_HILL_0BE2D5700 }}
          action: "close"
